services:
    bingemer_inwx_bundle:
        class: Bingemer\InwxBundle\BingemerInwxBundle\Classes\Domrobot
        arguments: ["%inwx_url%", "%locale%", "%kernel.cache_dir%", "%inwx_user%", "%inwx_pass%"]