<?php
/**
 * Created by PhpStorm.
 * User: joerg
 * Date: 14.02.16
 * Time: 12:55
 */
namespace Bingemer\InwxBundle;


use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class BingemerInwxBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }
}